config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Posts
  root to: "posts#index"

  # Users resourse

  # users_path
  resources :users, only: [:index,:show, :new,:create,:edit,:update,:destroy] # сам user
  resource :session, only: [:new,:create,:destroy] # ресурс сессии, тут будут создаваться сессии для user

  # delete '/logout', to: 'sessions#destroy'

  # Books resourse
  resources :books, only: [:index, :new, :create, :edit, :update, :show, :destroy] # ресурс для books

  # Authors resourse
  resources :authors, only: [:index, :new, :create, :edit, :update, :show, :destroy] # ресурс для authors

  # Genres resourse
  resources :genres, only: [:index, :new, :create, :destroy, :edit, :update] # ресурс для genres

end

app/models/book.rb
class Book < ApplicationRecord
  #TODO Проверка валедации
  validates :title, presence: true
  validates :genre, presence: true
  validates :author, presence: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :check_admin, only: [:new, :create, :edit, :update, :destroy]

  # Отображение списка всех книг
  def index
    @books = Book.all
  end

  # Отображение формы для создания новой книги
  def new
    @book = Book.new()
  end

  # Создание новой книги
  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to books_path, notice: "Книга добавлена"
    else
      handle_adding_errors
      redirect_to new_book_path
    end
  end

  # Отображение формы редактирования книги
  def edit
    # Добавьте код для отображения формы редактирования книги
  end

  # Обновление информации о книге
  def update
    # Добавьте код для обновления информации о книге
  end

  # Отображение информации о книге по ее ID
  def show
    @book = Book.find_by(id: params[:id])

    if @book.present?
      render "show"
    else
      render file: "#{Rails.root}/public/404.html", layout: false, status: :not_found
    end
  end

  # Удаление книги
  def destroy
    # Добавьте код для удаления книги
  end

  # Приватный метод для извлечения параметров книги из формы
  private

  def book_params
    params.require(:book).permit(:title, :description, :author, :year, :genre)
  end

  # Приватный метод для обработки ошибок при создании книги
  def handle_adding_errors
    # Добавьте код для обработки ошибок при создании книги
  end
end

app/views/books/index.html.erb
<div class="block">
  <% @books.each do |book| %>
    <%= link_to book.title, book_path(book.id) %>
  <% end %>
</div>

app/views/books/new.html.erb
<div class="block">
  <h2 class="title-main">Регистрация пользоватлея</h2>
  <div class="form">
    <%= form_with model: @book do |f|%>
      <%# Имя %>
      <div class="form-main">
        <%# Название %>
        <div class="form-group">
          <%= f.label :title, "Название".html_safe, class: "form-lable" %>
          <%= f.text_field :title, class: "form-text_field" %>
        </div>
        <%# Описание %>
        <div class="form-group">
          <%= f.label :description, "Описание".html_safe, class: "form-lable" %>
          <%= f.text_area :description, class: "form-text_area" %>
          <div class="password-visibility">
            <span id="last-char"></span>
          </div>
        </div>
        <%# Автор\Авторы %>
        <div class="form-group">
          <%= f.label :author, "Автор".html_safe, class: "form-lable" %>
          <%= f.text_field :author, class: "form-text_field" %>
        </div>
        <%# Год %>
        <div class="form-group">
          <%= f.label :year, "Год выпуска", class: "form-lable" %>
          <%= f.text_field :year, class: "form-text_field" %>
        </div>
        <%# Жанр %>
        <div class="form-group">
          <%= f.label :genre, "Жанр".html_safe, class: "form-lable" %>
          <%= f.text_field :genre, class: "form-text_field" %>
        </div>
        <%# Кнопка регистрации %>
        <%= f.submit "Добавить в коллекцию", class: "form-submit"%>
      </div>
    <% end %>
  </div>
</div>

app/views/books/show.html.erb
<div class="block">
  <h2><%= @book.title %></h2>
  <p><%= @book.description %></p>
  <%= link_to "Редактровать", edit_book_path(@book.id) %>
  <%= link_to "Коллекция", books_path %>
</div>