config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Posts
  root to: "posts#index"

  # Users resourse

  # users_path
  resources :users, only: [:index,:show, :new,:create,:edit,:update,:destroy] # сам user
  resource :session, only: [:new,:create,:destroy] # ресурс сессии, тут будут создаваться сессии для user

  # delete '/logout', to: 'sessions#destroy'

  # Books resourse
  resources :books, only: [:index, :new, :create, :edit, :update, :show, :destroy] # ресурс для books

  # Authors resourse
  resources :authors, only: [:index, :new, :create, :edit, :update, :show, :destroy] # ресурс для authors

  # Genres resourse
  resources :genres, only: [:index, :new, :create, :destroy, :edit, :update] # ресурс для genres

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= @page_title || "Книговед" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class="container">
      <div class="flash-container">
        <% if flash[:notice] %>
          <div class="flash-message alert-success">
            <%= flash[:notice] %>
          </div>
        <% end %>
        <% if flash[:alert] %>
          <div class="flash-message alert-danger">
            <%= flash[:alert] %>
          </div>
        <% end %>
      </div>
      <div class="header">
        <div class="profile-panel">
          <% if current_user %>
            <%= "#{current_user.name}, #{current_user.age}" %>
            <%= button_to "Выйти", session_path, method: :delete %>
          <% else %>
            <%= link_to "Вход", new_session_path, class: "profile-link" %>
            <%= link_to "Регистрация", new_user_path, class: "profile-link" %>
          <% end %>
        </div>
        <div class="logo-panel">
          <%= link_to "Книговед", root_path, class: "logo-title" %>
          <div class="logo-subtitle">Лучше в мире нет</div>
        </div>
        <hr class="line">
        <div class="navbar">
          <ul>
            <li class="navbar-item"><%= link_to "Читатели",users_path, class: "navbar-link" %></li>
            <li class="navbar-item"><%= link_to "Коллекция",books_path, class: "navbar-link" %></li>
            <% if current_user%>
              <li class="navbar-item"><%= link_to "Добавить книгу", new_book_path, class: "navbar-link" %></li>
            <% end %>
          </ul>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>